# Generated by Django 5.0.6 on 2024-06-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_simpleuser_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
    ]
